if ((typeof (jQuery)) == typeof (undefined)) { document.write('<script type="text/javascript" language="javascript" src="http://www.uuu9.com/skin2010/js/j.js"><\/script>'); }
if ((typeof (SSOT)) == typeof (undefined)) { document.write('<script type="text/javascript" language="javascript" src="http://devapp.uuu9.com/js/tool/SSOT.js"><\/script>'); }

//css
document.writeln("<style>");
document.writeln("*{ padding:0; margin:0;}");
document.writeln(".r_topnav_box{font-size:12px; background:url(top_nav_bj.gif) 0 0 repeat-x; height:87px; width:100%; position:relative;z-index:9999;}");
document.writeln(".r_topnav_box a{ text-decoration:none;}");
document.writeln(".r_topnav_box a:hover{ text-decoration:underline;}");
document.writeln(".r_topnav_box,.r_u9logo a,.v_allnav a,.r_admin_link a,.r_login_link a{color:#666;}");
document.writeln(".r_admin_link a.r_blue,.r_login_link span a{color:#333399;}");
document.writeln(".r_u9logo a:hover,.r_admin_link a:hover{color:#f30;}");
document.writeln(".r_pngbj{height:3px; background:url(pngbj.png) 0 0 repeat-x; overflow:hidden; width:100%; position:absolute; bottom:-3px;_background:none; z-index:9999;}");
document.writeln(".r_topnav{width:960px; margin:auto; height:36px;}");
document.writeln(".r_topbar_box{width:535px; float:left;}");
document.writeln(".r_u9logo{width:69px; height:37px; background:url(ico_ui.gif) -78px -176px no-repeat; line-height:37px; padding-left:20px; float:left;}");
document.writeln(".r_navlist{width:446px; height:37px; position:relative; z-index:99999; float:right;}");
document.writeln(".v_webnav{width:90px; height:37px; position:absolute;z-index:9999; background:url(ico_ui.gif) 0 0 no-repeat;}");
document.writeln(".v_webnav.nav_1{top:0; left:0;}");
document.writeln(".v_webnav.nav_2{top:0; left:89px;}");
document.writeln(".v_webnav.nav_3{top:0; left:178px;}");
document.writeln(".v_webnav.nav_4{top:0; left:267px;}");
document.writeln(".v_webnav.nav_5{top:0; left:356px;}");
document.writeln(".v_allnav{height:37px; line-height:37px;}");
document.writeln(".v_allnav span{padding-left:15px;}");
document.writeln(".v_navbox{width:110px; position:absolute; top:32px; left:-10px; z-index:9999;filter:progid:DXImageTransform.Microsoft.Shadow(color=\'#cccccc\',Direction=135,Strength=2); -moz-box-shadow:1px 1px 2px #cccccc}");
document.writeln(".v_nav_bottom {background:url(bottom.gif) 0 0 no-repeat; height:9px; font-size:0}");
document.writeln(".v_nav_top {background:url(top.gif) 0 0 no-repeat; height:13px; font-size:0}");
document.writeln(".v_webnav .v_allnav.v_active span a{ color:#f30;}");
document.writeln(".v_webnav .v_allnav.v_active{ background:url(ico_ui.gif) 0 -41px no-repeat;}");
document.writeln(".v_navbar{border:solid 1px #999999;padding:0 3px 0 3px; background:#f7f7f7;border-bottom:none;border-top:none;}");
document.writeln(".v_navlist{padding:0 5px 0 5px; background:#FFF;border:#dedede 1px solid; border-bottom:none;border-top:none;}");
document.writeln(".v_navlist a p{ display:block;padding-left:15px;color:#333399; height:24px; line-height:24px; background:url(ico_02.gif) 5px 10px no-repeat;}");
document.writeln(".v_navlist a:hover p{ display:block;padding-left:15px; color:#ff3300; text-decoration:underline; height:24px; line-height:24px; background:url(ico_02_active.gif) #e3e3e3 5px 10px no-repeat;}");
document.writeln(".r_login_box{width:410px; float:right;}");
document.writeln(".r_formbox{width:290px; height:20px; margin:9px 0 0 0; float:left;}");
document.writeln(".r_formbox .navbox_s{width:55px; height:20px; background:url(ico_ui.gif) -34px -104px no-repeat; position:relative; z-index:99999; float:left;}");
document.writeln(".navbox_s  span{ display:block; height:20px; line-height:20px;text-indent:5px; cursor:pointer}");
document.writeln(".navbox_s.hover {background:url(http://www.uuu9.com/skin2010/images/ui3.png) 0 -49px no-repeat;}");
document.writeln(".navbox_s div{ position:absolute; top:20px; left:0; width:58px; border:solid 1px #d9d9d9; background:#fff;padding:5px 0;}");
document.writeln(".navbox_s div a { display: block; line-height:22px; text-decoration:none; color:#333;text-indent:10px}");
document.writeln(".navbox_s div a:hover { background:#1051C9; color:#fff}");
document.writeln(".r_input_admin { width:86px; color:#ccc; font-size:12px; float:left; height:16px; background:url(ico_ui.gif) 0 -81px no-repeat; border:0; line-height:16px; padding:2px;}");
document.writeln(".r_input_admin_mm { width:86px; color:#ccc; font-size:12px; float:left; height:16px; background:url(ico_ui.gif) 0 -81px no-repeat; border:0; line-height:16px; padding:2px; margin-left:5px;}");
document.writeln(".r_input_admin_button { width:40px; height:20px; background:url(ico_ui.gif) -50px -128px no-repeat; font-size:12px; color:#fff; cursor: pointer; border:none;float:left; margin:0 0 0 5px; *display:inline;}");
document.writeln(".r_admin_link{ float:right; line-height:37px;}");
document.writeln(".r_robin_hou{ height:37px; line-height:37px; width:270px; float:right;}");
document.writeln(".r_admin_pic{width:24px; height:24px; padding:3px; background:url(admin_pic.gif) 0 0 no-repeat; float:left; margin-top:3px; margin-right:5px;}");
document.writeln(".r_admin_pic img{width:24px; height:24px; display:block;}");
document.writeln(".r_admin_pic a img{ border:0;}");
document.writeln(".r_login_link{width:226px; float:left;}");
document.writeln(".r_login_link a{ padding:0 5px;}");
document.writeln(".r_login_link span a{ font-weight:bold;}");
document.writeln("");
document.writeln("</style>");
//html
document.writeln("<div class=\"r_topnav_box\">");
document.writeln("        <div style=\"margin: 0 auto; width: 960px\" id=\"top\">");
document.writeln("        </div>");
document.writeln("        <script src=\"http://biz5.sandai.net/portal/uuu9/top.js\"></script>");
document.writeln("        <div class=\"r_topnav\">");
document.writeln("            <div class=\"r_topbar_box\">");
document.writeln("                <div class=\"r_u9logo\">");
document.writeln("                    <a href=\"http://www.uuu9.com/\" target=\"_blank\">游久网首页</a></div>");
document.writeln("                <div class=\"r_navlist\">");
document.writeln("                    <div class=\"v_webnav nav_1\">");
document.writeln("                        <div class=\"v_allnav\">");
document.writeln("                            <span><a href=\"http://news.uuu9.com/\" target=\"_blank\">最新报道</a></span></div>");
document.writeln("                        <div class=\"v_navbox\" style=\"display: none;\">");
document.writeln("                            <div class=\"v_nav_top\">");
document.writeln("                            </div>");
document.writeln("                            <div class=\"v_navbar\">");
document.writeln("                                <div class=\"v_navlist\">");
document.writeln("                                    <a href=\"http://news.uuu9.com/\" target=\"_blank\">");
document.writeln("                                        <p>");
document.writeln("                                            新闻</p>");
document.writeln("                                    </a><a href=\"http://newgame.uuu9.com/\" target=\"_blank\">");
document.writeln("                                        <p>");
document.writeln("                                            新游</p>");
document.writeln("                                    </a><a href=\"http://chanye.uuu9.com/\" target=\"_blank\">");
document.writeln("                                        <p>");
document.writeln("                                            产业</p>");
document.writeln("                                    </a>");
document.writeln("                                </div>");
document.writeln("                            </div>");
document.writeln("                            <div class=\"v_nav_bottom\">");
document.writeln("                            </div>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                    <div class=\"v_webnav nav_2\">");
document.writeln("                        <div class=\"v_allnav\">");
document.writeln("                            <span><a href=\"http://news.uuu9.com/\" target=\"_blank\">热门游戏</a></span></div>");
document.writeln("                        <div class=\"v_navbox\" style=\"display: none;\">");
document.writeln("                            <div class=\"v_nav_top\">");
document.writeln("                            </div>");
document.writeln("                            <div class=\"v_navbar\">");
document.writeln("                                <div class=\"v_navlist\">");
document.writeln("                                    <a href=\"http://zt2.uuu9.com/\" target=\"_blank\">");
document.writeln("                                        <p>");
document.writeln("                                            征途2</p>");
document.writeln("                                    </a><a href=\"http://ldj.uuu9.com/\" target=\"_blank\">");
document.writeln("                                        <p>");
document.writeln("                                            鹿鼎记</p>");
document.writeln("                                    </a><a href=\"http://lol.uuu9.com/\" target=\"_blank\">");
document.writeln("                                        <p>");
document.writeln("                                            英雄联盟</p>");
document.writeln("                                    </a><a href=\"http://csxy.uuu9.com/\" target=\"_blank\">");
document.writeln("                                        <p>");
document.writeln("                                            创世西游</p>");
document.writeln("                                    </a><a href=\"http://wow.uuu9.com/\" target=\"_blank\">");
document.writeln("                                        <p>");
document.writeln("                                            魔兽世界</p>");
document.writeln("                                    </a><a href=\"http://sc2.uuu9.com/\" target=\"_blank\">");
document.writeln("                                        <p>");
document.writeln("                                            星际争霸2</p>");
document.writeln("                                    </a><a href=\"http://dnf.uuu9.com/\" target=\"_blank\">");
document.writeln("                                        <p>");
document.writeln("                                            地下城与勇士</p>");
document.writeln("                                    </a>");
document.writeln("                                </div>");
document.writeln("                            </div>");
document.writeln("                            <div class=\"v_nav_bottom\">");
document.writeln("                            </div>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                    <div class=\"v_webnav nav_3\">");
document.writeln("                        <div class=\"v_allnav\">");
document.writeln("                            <span><a href=\"http://uuu9.com/\" target=\"_blank\">特别企划</a></span></div>");
document.writeln("                        <div class=\"v_navbox\" style=\"display: none;\">");
document.writeln("                            <div class=\"v_nav_top\">");
document.writeln("                            </div>");
document.writeln("                            <div class=\"v_navbar\">");
document.writeln("                                <div class=\"v_navlist\">");
document.writeln("                                    <a href=\"http://yy.uuu9.com/\" target=\"_blank\">");
document.writeln("                                        <p>");
document.writeln("                                            游久有约</p>");
document.writeln("                                    </a><a href=\"http://news.uuu9.com/shuoshi/\" target=\"_blank\">");
document.writeln("                                        <p>");
document.writeln("                                            游久说事</p>");
document.writeln("                                    </a><a href=\"http://news.uuu9.com/hrzf/\" target=\"_blank\">");
document.writeln("                                        <p>");
document.writeln("                                            网络红人</p>");
document.writeln("                                    </a><a href=\"http://news.uuu9.com/zt/\" target=\"_blank\">");
document.writeln("                                        <p>");
document.writeln("                                            焦点话题</p>");
document.writeln("                                    </a><a href=\"http://chanye.uuu9.com/oneday/\" target=\"_blank\">");
document.writeln("                                        <p>");
document.writeln("                                            游戏人的一天</p>");
document.writeln("                                    </a>");
document.writeln("                                </div>");
document.writeln("                            </div>");
document.writeln("                            <div class=\"v_nav_bottom\">");
document.writeln("                            </div>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                    <div class=\"v_webnav nav_4\">");
document.writeln("                        <div class=\"v_allnav\">");
document.writeln("                            <span><a href=\"http://war3.uuu9.com/\" target=\"_blank\">魔兽争霸3</a></span></div>");
document.writeln("                        <div class=\"v_navbox\" style=\"display: none;\">");
document.writeln("                            <div class=\"v_nav_top\">");
document.writeln("                            </div>");
document.writeln("                            <div class=\"v_navbar\">");
document.writeln("                                <div class=\"v_navlist\">");
document.writeln("                                    <a href=\"http://dota.uuu9.com/\" target=\"_blank\">");
document.writeln("                                        <p>");
document.writeln("                                            DOTA</p>");
document.writeln("                                    </a><a href=\"http://maps.uuu9.com/\" target=\"_blank\">");
document.writeln("                                        <p>");
document.writeln("                                            地图库</p>");
document.writeln("                                    </a><a href=\"http://war3.uuu9.com/\" target=\"_blank\">");
document.writeln("                                        <p>");
document.writeln("                                            RPG地图下载</p>");
document.writeln("                                    </a>");
document.writeln("                                </div>");
document.writeln("                            </div>");
document.writeln("                            <div class=\"v_nav_bottom\">");
document.writeln("                            </div>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                    <div class=\"v_webnav nav_5\">");
document.writeln("                        <div class=\"v_allnav\">");
document.writeln("                            <span><a href=\"http://bbs.uuu9.com/\" target=\"_blank\">玩家社区</a></span></div>");
document.writeln("                        <div class=\"v_navbox\" style=\"display: none;\">");
document.writeln("                            <div class=\"v_nav_top\">");
document.writeln("                            </div>");
document.writeln("                            <div class=\"v_navbar\">");
document.writeln("                                <div class=\"v_navlist\">");
document.writeln("                                    <a href=\"http://bbs.uuu9.com/\" target=\"_blank\">");
document.writeln("                                        <p>");
document.writeln("                                            游久社区</p>");
document.writeln("                                    </a><a href=\"http://sc2bbs.uuu9.com/\" target=\"_blank\">");
document.writeln("                                        <p>");
document.writeln("                                            星际争霸2</p>");
document.writeln("                                    </a><a href=\"http://www.zt2cn.com/\" target=\"_blank\">");
document.writeln("                                        <p>");
document.writeln("                                            征途兔之窝</p>");
document.writeln("                                    </a>");
document.writeln("                                </div>");
document.writeln("                            </div>");
document.writeln("                            <div class=\"v_nav_bottom\">");
document.writeln("                            </div>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("            <div class=\"r_login_box\">");
document.writeln("                <div class=\"r_login_qian\">");
document.writeln("                    <form method=\"post\" id=\"ssotopform\" action=\"http://u.uuu9.com/logging.php?ac=login\" onsubmit=\"return uuu9_as_top_check();\">");
document.writeln("                    <div class=\"r_formbox\">");
document.writeln("                        <input type=\"hidden\" id=\"satoploginfield\" name=\"loginfield\" value=\"username\" />");
document.writeln("                        <input type=\"hidden\" id=\"satopreferer\" name=\"referer\" value=\"http://www.uuu9.com\"/>");
document.writeln("                        <input type=\"hidden\" name=\"h301\" value=\"1\" />");
document.writeln("                        <div class=\"navbox_s\">");
document.writeln("                            <span>用户名</span>");
document.writeln("                            <div>");
document.writeln("                                <a href=\"#\" pname=\"email\">Email</a> <a href=\"#\" pname=\"username\">用户名</a>");
document.writeln("                            </div>");
document.writeln("                        </div>");
document.writeln("                        <input type=\"text\" id=\"satopusername\" name=\"username\" onblur=\"this.value=this.value==\'\'?\'请输入\':this.value\" onfocus=\"this.value=this.value==\'请输入\'?\'\':this.value\"");
document.writeln("                            value=\"请输入\" class=\"r_input_admin\" />");
document.writeln("                        <input type=\"password\" id=\"satoppassword\" name=\"password\" class=\"r_input_admin_mm\" />");
document.writeln("                        <input type=\"submit\" value=\"登录\" class=\"r_input_admin_button\" />");
document.writeln("                    </div>");
document.writeln("                    </form>");
document.writeln("                    <div class=\"r_admin_link\">");
document.writeln("                        <a href=\"#\">忘记密码?</a> <a href=\"#\" class=\"r_blue\">新用户注册</a></div>");
document.writeln("                </div>");
document.writeln("                <div class=\"r_robin_hou\" style=\"display: none;\">");
document.writeln("                    <div class=\"r_admin_pic\">");
document.writeln("                        <a href=\"#\">");
document.writeln("                            <img id=\"satopimgd\" src=\"http://bbs.uuu9.com/uc_server/avatar.php?uid=4308129&size=small\" /></a>");
document.writeln("                    </div>");
document.writeln("                    <div class=\"r_login_link\">");
document.writeln("                        欢迎你,<span><a href=\"#\" id=\"satopunamed\"></a></span>|<a href=\"#\" id=\"satopmsgd\">loading...</a>|<a id=\"satopexit\" href=\"http://u.uuu9.com/logging.php?ac=logout\">退出</a>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("        <div class=\"r_pngbj\">");
document.writeln("        </div>");
document.writeln("    </div>");